// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.28;
import {PullCredit} from "../src/lib/PullCredit.sol";
import {SplitPaymentsV1 as Split} from "../src/SplitPaymentsV1.sol";
import {GroupEscrowV1 as Group1} from "../src/GroupEscrowV1.sol";
import {GroupEscrowV2 as Group2} from "../src/GroupEscrowV2.sol";
import {DeliveryEscrowV1 as Delivery} from "../src/DeliveryEscrowV1.sol";
import {AttendanceBondV1 as Attend} from "../src/AttendanceBondV1.sol";
import {MilestoneEscrowV1 as Milestones} from "../src/MilestoneEscrowV1.sol";
import {RewardsDistributorV1 as Rewards} from "../src/RewardsDistributorV1.sol";
interface NativeVm { function chainId(uint256) external; function warp(uint256) external; function deal(address,uint256) external; function prank(address) external; function expectRevert() external; function expectRevert(bytes4) external; }
contract NativeReceiver {
  bool public reject = true; bool public reentered; PullCredit public target; bytes32 public id;
  function configure(PullCredit t,bytes32 box,bool fail) external {target=t;id=box;reject=fail;}
  receive() external payable { require(!reject,"rejected"); (reentered,)=address(target).call(abi.encodeCall(target.withdrawFor,(id,address(this)))); }
}
contract NativeMONTest {
  NativeVm constant vm=NativeVm(address(uint160(uint256(keccak256("hevm cheat code")))));
  address alice=address(0xA11); address bob=address(0xB11); address payer=address(0xC11); bytes32 constant META=keccak256("MON rules");
  function setUp() public {vm.chainId(10143);vm.warp(1000);vm.deal(payer,100 ether);vm.deal(address(this),100 ether);}
  function eq(uint256 a,uint256 b) internal pure {require(a==b,"amount mismatch");}
  function conserve(PullCredit p) internal view {eq(p.totalDeposited(),p.totalLocked()+p.totalCredits()+p.totalWithdrawn());require(address(p).balance>=p.totalLocked()+p.totalCredits(),"insolvent");}
  function recipients() internal view returns(address[] memory a,uint16[] memory b){a=new address[](2);a[0]=alice;a[1]=bob;b=new uint16[](2);b[0]=7000;b[1]=3000;}
  function split() internal returns(Split s,bytes32 id){s=new Split(address(0),address(this));(address[] memory a,uint16[] memory b)=recipients();id=s.createSplit(Split.Terms(a,b,META),0);}
  function testSplitNativePaymentAndWithdrawal() public {(Split s,bytes32 id)=split();vm.prank(payer);s.pay{value:1 ether}(id,1 ether,0);eq(s.creditForBox(id,alice),0.7 ether);s.withdrawFor(id,alice);eq(alice.balance,0.7 ether);s.withdrawFor(id,bob);eq(bob.balance,0.3 ether);conserve(s);}
  function testNativeUnderOverAndZeroValueRollbackNonce() public {(Split s,bytes32 id)=split();for(uint256 i;i<3;i++){uint256 value=i==0?0:i==1?1 ether-1:1 ether+1;vm.expectRevert(PullCredit.TransferAmountMismatch.selector);vm.prank(payer);s.pay{value:value}(id,1 ether,0);eq(s.totalDeposited(),0);require(!s.usedNonce(payer,0));}vm.prank(payer);s.pay{value:1 ether}(id,1 ether,0);conserve(s);}
  function testNativeReceiverFailurePreservesCreditAndReentryCannotDoubleWithdraw() public {NativeReceiver receiver=new NativeReceiver();Split s=new Split(address(0),address(this));address[] memory a=new address[](2);uint16[] memory b=new uint16[](2);a[0]=alice;a[1]=address(receiver);b[0]=5000;b[1]=5000;bytes32 id=s.createSplit(Split.Terms(a,b,META),0);s.pay{value:1 ether}(id,1 ether,0);receiver.configure(s,id,true);vm.expectRevert(PullCredit.NativeTransferFailed.selector);s.withdrawFor(id,address(receiver));eq(s.creditForBox(id,address(receiver)),0.5 ether);eq(s.withdrawnForBox(id,address(receiver)),0);s.withdrawFor(id,alice);eq(alice.balance,0.5 ether);receiver.configure(s,id,false);s.withdrawFor(id,address(receiver));require(!receiver.reentered());eq(address(receiver).balance,0.5 ether);conserve(s);}
  function testForcedSurplusCreatesNoEntitlementAndDirectSendRejects() public {(Split s,bytes32 id)=split();(bool ok,)=address(s).call{value:1}("");require(!ok);vm.deal(address(s),3 ether);eq(s.creditForBox(id,payer),0);eq(s.totalDeposited(),0);vm.expectRevert(PullCredit.NothingToWithdraw.selector);s.withdrawFor(id,payer);conserve(s);}
  function testGroupV1LeaveNativeRefund() public {Group1 g=new Group1(address(0),address(this));bytes32 id=g.createGroup(Group1.Terms(alice,1 ether,2,3,1000,2000,3000,META),0);vm.prank(payer);g.contribute{value:1 ether}(id);vm.prank(payer);g.leave(id);eq(g.creditForBox(id,payer),1 ether);g.withdrawFor(id,payer);eq(payer.balance,100 ether);eq(address(g).balance,0);}
  function testGroupV2SuccessNativeFixedSplit() public {Group2 g=new Group2(address(0),address(this));(address[] memory a,uint16[] memory b)=recipients();bytes32 id=g.createGroup(Group2.Terms(1 ether,2,3,1000,2000,3000,a,b,META),0);g.contribute{value:1 ether}(id);vm.prank(payer);g.contribute{value:1 ether}(id);vm.expectRevert();g.settle(id);vm.warp(3000);g.finalize(id);g.settle(id);g.withdrawFor(id,alice);eq(alice.balance,1.4 ether);eq(g.creditForBox(id,bob),0.6 ether);conserve(g);}
  function testDeliveryNativeAcceptanceAndRefund() public {Delivery d=new Delivery(address(0),address(this));vm.prank(alice);bytes32 id=d.createOffer(Delivery.Terms(payer,alice,1 ether,2000,3600,3600,86400,META),0);vm.prank(payer);d.fund{value:1 ether}(id);vm.prank(alice);d.submitDelivery(id,META);vm.prank(payer);d.accept(id);d.withdrawFor(id,alice);eq(alice.balance,1 ether);conserve(d);}
  function testDeliveryWrongNativeValueCannotFund() public {Delivery d=new Delivery(address(0),address(this));vm.prank(alice);bytes32 id=d.createOffer(Delivery.Terms(payer,alice,1 ether,2000,3600,3600,86400,META),0);vm.expectRevert(PullCredit.TransferAmountMismatch.selector);vm.prank(payer);d.fund{value:1}(id);eq(d.totalLocked(),0);vm.prank(payer);d.fund{value:1 ether}(id);vm.warp(4600);d.refundAfterMissingDelivery(id);d.withdrawFor(id,payer);eq(payer.balance,100 ether);conserve(d);}
  function testAttendNativeLeaveAndNoShow() public {Attend a=new Attend(address(0),address(this));bytes32 id=a.createEvent(Attend.Terms(1 ether,2,2000,4000,5000,3000,6000,8000,86400,2500,bob,alice,META),0);vm.prank(payer);a.register{value:1 ether}(id);vm.warp(8000);a.finalizeNoShow(id,payer);a.withdrawFor(id,payer);a.withdrawFor(id,bob);eq(payer.balance,99.75 ether);eq(bob.balance,0.25 ether);conserve(a);}
  function testMilestonesNativeReleasesOnlyAcceptedStage() public {Milestones m=new Milestones(address(0),address(this));Milestones.Stage[] memory stages=new Milestones.Stage[](2);stages[0]=Milestones.Stage(0.3 ether,3600,3600);stages[1]=Milestones.Stage(0.7 ether,3600,3600);vm.prank(alice);bytes32 id=m.createOffer(Milestones.Terms(payer,alice,2000,86400,stages,META),0);vm.prank(payer);m.fund{value:1 ether}(id);vm.prank(alice);m.submitDelivery(id,0,META);vm.prank(payer);m.accept(id,0);m.withdrawFor(id,alice);eq(alice.balance,0.3 ether);eq(m.locked(id),0.7 ether);vm.prank(alice);m.refundBySeller(id,1);m.withdrawFor(id,payer);eq(payer.balance,99.7 ether);conserve(m);}
  function testRewardsNativeAtomicFundingClaimAndExpiry() public {Rewards r=new Rewards(address(0),address(this));address[] memory a=new address[](2);a[0]=alice;a[1]=bob;uint256[] memory amounts=new uint256[](2);amounts[0]=0.4 ether;amounts[1]=0.6 ether;Rewards.Terms memory terms=Rewards.Terms(a,amounts,2000,3000,META);vm.expectRevert(PullCredit.TransferAmountMismatch.selector);vm.prank(payer);r.createAndFundBatch{value:1}(terms,0);eq(r.totalDeposited(),0);vm.prank(payer);bytes32 id=r.createAndFundBatch{value:1 ether}(terms,0);vm.warp(2000);r.claimFor(id,alice);vm.warp(3000);vm.prank(payer);r.reclaimExpired(id);r.withdrawFor(id,alice);r.withdrawFor(id,payer);eq(alice.balance,0.4 ether);eq(payer.balance,99.6 ether);conserve(r);}
  function testFuzzNativeConservation(uint96 seed) public {(Split s,bytes32 id)=split();uint256 amount=uint256(seed)+1;vm.deal(payer,amount);vm.prank(payer);s.pay{value:amount}(id,amount,0);if(s.creditForBox(id,alice)>0)s.withdrawFor(id,alice);if(s.creditForBox(id,bob)>0)s.withdrawFor(id,bob);eq(alice.balance+bob.balance,amount);eq(address(s).balance,0);conserve(s);}
}
