// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.28;
import {RewardsDistributorV1 as Rewards} from "../src/RewardsDistributorV1.sol";
import {PullCredit} from "../src/lib/PullCredit.sol";
import {MockToken} from "./MockToken.sol";
interface RewardsVm {function chainId(uint256) external;function warp(uint256) external;function prank(address) external;function expectRevert() external;function expectRevert(bytes4) external;}
contract RewardsDistributorV1Test {
    RewardsVm constant vm=RewardsVm(address(uint160(uint256(keccak256("hevm cheat code")))));
    Rewards rewards;MockToken token;address creator=address(1);address alice=address(2);address bob=address(3);bytes32 id;
    function setUp() public {vm.chainId(10143);vm.warp(1000);token=new MockToken();rewards=new Rewards(address(token),address(this));token.mint(creator,1000000);vm.prank(creator);token.approve(address(rewards),type(uint256).max);}
    function terms() internal view returns(Rewards.Terms memory t) {t.recipients=new address[](2);t.amounts=new uint256[](2);t.recipients[0]=alice;t.recipients[1]=bob;t.amounts[0]=31;t.amounts[1]=70;t.claimStart=2000;t.claimDeadline=3000;t.metadataHash=keccak256("public list");}
    function create() internal {vm.prank(creator);id=rewards.createAndFundBatch(terms(),0);}
    function eq(uint256 a,uint256 b) internal pure {require(a==b,"mismatch");}
    function invariantFunds() internal view {eq(rewards.totalDeposited(),rewards.totalLocked()+rewards.totalCredits()+rewards.totalWithdrawn());require(token.balanceOf(address(rewards))>=rewards.totalLocked()+rewards.totalCredits(),"insolvent");}
    function testAtomicCreateAndFundThenFixedClaims() public {create();eq(rewards.locked(id),101);eq(rewards.getBatch(id).totalAmount,101);vm.warp(2000);rewards.claimFor(id,alice);eq(rewards.creditOf(alice),31);eq(rewards.creditOf(address(this)),0);rewards.claimFor(id,bob);eq(rewards.locked(id),0);eq(rewards.getBatch(id).claimedCount,2);rewards.withdrawFor(id,alice);rewards.withdrawFor(id,bob);invariantFunds();}
    function testNoListWithoutActualWholeFunding() public {vm.prank(creator);token.approve(address(rewards),100);vm.expectRevert();create();eq(rewards.totalDeposited(),0);bytes32 missing=rewards.boxIdFor(creator,0);vm.expectRevert(PullCredit.InvalidState.selector);rewards.getBatch(missing);}
    function testEmptyOverLimitAndMismatchedListsReject() public {Rewards.Terms memory t=terms();t.recipients=new address[](0);vm.expectRevert();rewards.createAndFundBatch(t,0);t=terms();t.amounts=new uint256[](1);vm.expectRevert();rewards.createAndFundBatch(t,0);t=terms();t.recipients=new address[](101);t.amounts=new uint256[](101);vm.expectRevert();rewards.createAndFundBatch(t,0);}
    function testDuplicateUnsortedZeroAndSelfRecipientsReject() public {Rewards.Terms memory t=terms();t.recipients[1]=alice;vm.expectRevert();rewards.createAndFundBatch(t,0);t=terms();t.recipients[0]=address(4);vm.expectRevert();rewards.createAndFundBatch(t,0);t=terms();t.recipients[0]=address(0);vm.expectRevert();rewards.createAndFundBatch(t,0);t=terms();t.recipients[1]=address(rewards);vm.expectRevert();rewards.createAndFundBatch(t,0);}
    function testZeroOverflowAndBadTimesReject() public {Rewards.Terms memory t=terms();t.amounts[0]=0;vm.expectRevert();rewards.createAndFundBatch(t,0);t=terms();t.amounts[0]=type(uint256).max;vm.expectRevert();rewards.createAndFundBatch(t,0);t=terms();t.claimStart=t.claimDeadline;vm.expectRevert();rewards.createAndFundBatch(t,0);t=terms();t.claimStart=900;t.claimDeadline=1000;vm.expectRevert();rewards.createAndFundBatch(t,0);}
    function testClaimsAreSingleAndNonListedCannotClaim() public {create();vm.warp(2000);vm.expectRevert(PullCredit.NotAuthorized.selector);rewards.claimFor(id,creator);rewards.claimFor(id,alice);vm.expectRevert(PullCredit.AlreadyProcessed.selector);rewards.claimFor(id,alice);invariantFunds();}
    function testExactStartAndExpiryHaveNoOverlap() public {create();vm.warp(1999);vm.expectRevert(PullCredit.WindowNotStarted.selector);rewards.claimFor(id,alice);vm.warp(2000);rewards.claimFor(id,alice);vm.warp(2999);vm.expectRevert(PullCredit.WindowNotStarted.selector);vm.prank(creator);rewards.reclaimExpired(id);vm.warp(3000);vm.expectRevert(PullCredit.WindowClosed.selector);rewards.claimFor(id,bob);vm.prank(creator);rewards.reclaimExpired(id);invariantFunds();}
    function testExpiryReclaimsOnlyUnclaimedAndCannotStealUnwithdrawnCredits() public {create();vm.warp(2000);rewards.claimFor(id,alice);vm.warp(3000);vm.prank(creator);rewards.reclaimExpired(id);eq(rewards.creditOf(creator),70);eq(rewards.creditOf(alice),31);rewards.withdrawFor(id,alice);eq(token.balanceOf(alice),31);invariantFunds();}
    function testOnlyOriginalCreatorReclaimsAndNoRepeatedReclaim() public {create();vm.warp(3000);vm.expectRevert(PullCredit.NotAuthorized.selector);rewards.reclaimExpired(id);vm.prank(creator);rewards.reclaimExpired(id);vm.expectRevert(PullCredit.AlreadyProcessed.selector);vm.prank(creator);rewards.reclaimExpired(id);eq(rewards.creditOf(creator),101);}
    function testFullyClaimedHasNothingToReclaim() public {create();vm.warp(2000);rewards.claimFor(id,alice);rewards.claimFor(id,bob);vm.warp(3000);vm.expectRevert(PullCredit.AlreadyProcessed.selector);vm.prank(creator);rewards.reclaimExpired(id);invariantFunds();}
    function testPauseBlocksCreationButNotClaimReclaimOrWithdraw() public {create();rewards.setIntakePaused(true);vm.expectRevert(PullCredit.IntakePaused.selector);vm.prank(creator);rewards.createAndFundBatch(terms(),0);vm.warp(2000);rewards.claimFor(id,alice);rewards.withdrawFor(id,alice);vm.warp(3000);vm.prank(creator);rewards.reclaimExpired(id);rewards.withdrawFor(id,creator);invariantFunds();}
    function testSaltCannotOverwriteAnExistingFundedList() public {create();vm.expectRevert(PullCredit.AlreadyProcessed.selector);vm.prank(creator);rewards.createAndFundBatch(terms(),0);eq(rewards.locked(id),101);invariantFunds();}
    function testTaxedFundingAndFailedWithdrawalRollBack() public {token.setFee(true);vm.expectRevert(PullCredit.TransferAmountMismatch.selector);create();eq(rewards.totalDeposited(),0);token.setFee(false);create();vm.warp(2000);rewards.claimFor(id,alice);token.setFail(true);vm.expectRevert();rewards.withdrawFor(id,alice);eq(rewards.creditOf(alice),31);invariantFunds();}
    function testOneRecipientAndCreatorAsRecipient() public {Rewards.Terms memory t=terms();t.recipients=new address[](1);t.amounts=new uint256[](1);t.recipients[0]=creator;t.amounts[0]=1;vm.prank(creator);id=rewards.createAndFundBatch(t,0);vm.warp(2000);rewards.claimFor(id,creator);eq(rewards.creditOf(creator),1);invariantFunds();}
    function testHundredRecipientBoundAndConstantTimeClaim() public {Rewards.Terms memory t=terms();t.recipients=new address[](100);t.amounts=new uint256[](100);for(uint256 n;n<100;++n){t.recipients[n]=address(uint160(n+100));t.amounts[n]=n+1;}vm.prank(creator);id=rewards.createAndFundBatch(t,0);eq(rewards.locked(id),5050);vm.warp(2000);rewards.claimFor(id,address(199));eq(rewards.creditOf(address(199)),100);vm.warp(3000);vm.prank(creator);rewards.reclaimExpired(id);eq(rewards.creditOf(creator),4950);invariantFunds();}
    function testFuzzClaimOrderAndExpiryConserve(uint96 first,uint96 second,bool chooseFirst) public {Rewards.Terms memory t=terms();t.amounts[0]=uint256(first)+1;t.amounts[1]=uint256(second)+1;token.mint(creator,t.amounts[0]+t.amounts[1]);vm.prank(creator);id=rewards.createAndFundBatch(t,0);vm.warp(2000);rewards.claimFor(id,chooseFirst?alice:bob);vm.warp(3000);vm.prank(creator);rewards.reclaimExpired(id);eq(rewards.creditOf(creator),chooseFirst?t.amounts[1]:t.amounts[0]);invariantFunds();}
}
